version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mysql-db
    restart: always